__init__.py
from app import create_app, socketio

app = create_app()

if __name__ == '__main__':
    socketio.run(app)

api/routes.py
from flask import Blueprint, request, current_app, make_response, jsonify
import jwt
from functools import wraps
import datetime
from sql import sql_master as database

import secrets

api = Blueprint('api', __name__, url_prefix='/api')


def token_required(f):
    @wraps(f)
    def decorated(*args, **kwargs):

        try:
            token = request.headers.get('token')  # http://127.0.0.1:5000/route?token=nv8h4994hv4
        except:
            return 'Authentication token is required.'

        try:
            jwt.decode(token, current_app.config['SECRET_KEY'])

        except:
            return 'Invalid authentication token.'

        return f(*args, **kwargs)

    return decorated


@api.route('/')
def index():
    return 'Welcome to the Dotops API!'


# Route for handling the login page logic
@api.route('/generate_token')
def generate_token():
    auth = request.authorization

    if auth and (auth.username != secrets.api_user or auth.password != secrets.api_password):
        return make_response('Could not verify!', 401, {'WWW-Authenticate' : 'Basic realm="Login Required'})

    elif auth and (auth.username == secrets.api_user and auth.password == secrets.api_password):
        token = jwt.encode({'user': auth.username, 'exp': datetime.datetime.utcnow() + datetime.timedelta(days=3)}, current_app.config['SECRET_KEY'])

        return token

    return make_response('Authorization is required!', 401, {'WWW-Authenticate': 'Basic realm="Login Required'})


@api.route('/active_game', methods=['GET', 'POST'])
@token_required
def active_game():
    json_post = jsonify({'status': database.read()[0],
                         'product': database.read()[1],
                         'duration': database.read()[2],
                         'name1': database.read()[3],
                         'name2': database.read()[4],
                         'name3': database.read()[5],
                         'manager_id': database.read()[6]
                         })

    if request.method == 'POST':
        json_post = request.get_json()

        database.update(json_post)

    return json_post

app/__init__.py
from flask import Flask
import os
from app.main import api, website


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = os.environ.get("secret_key")

    from .main import main, interface
    app.register_blueprint(main)
    app.register_blueprint(interface, url_prefix='/api')

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)
interface = Blueprint('interface', __name__)

main.py
from app import create_app, Flask

app = create_app()

if __name__ == '__main__':
    Flask.run(app)

website/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, session, current_app
from functools import wraps
from sql import sql_master as database
import os

from authlib.integrations.flask_client import OAuth

# OAuth config
oauth = OAuth(current_app)
oauth.register(
    name='google',
    client_id=os.getenv("GOOGLE_CLIENT_ID"),
    client_secret=os.getenv("GOOGLE_CLIENT_SECRET"),
    access_token_url='https://accounts.google.com/o/oauth2/token',
    access_token_params=None,
    authorize_url='https://accounts.google.com/o/oauth2/auth',
    authorize_params=None,
    api_base_url='https://www.googleapis.com/oauth2/v1/',
    userinfo_endpoint='https://openidconnect.googleapis.com/v1/userinfo',  # This is only needed if using openId to fetch user info
    client_kwargs={'scope': 'openid email profile'},
)


website = Blueprint('website', __name__)



def auth_required(f):
    @wraps(f)
    def decorated(*args, **kwargs):

        authorized_users = ['isaiah.jk.gordon@gmail.com']

        user = dict(session).get('email', None)
        # You would add a check here and use the user id or something to fetch
        # the other data for that user/check if they exist
        if user in authorized_users:
            return f(*args, **kwargs)

        elif user is None:
            return redirect(url_for('website.welcome'))

        elif user not in authorized_users:
            email = dict(session).get('email', None)
            return f'Access denied: Your account \" {email} \" is not authorized!'


    return decorated


@website.route('/')
@auth_required
def index():
    return render_template('home.html')

@website.route('/welcome')
def welcome():
    return render_template('index.html')


@website.route('/info')
def info():
    return render_template('info.html')


@website.route('/login')
def login():
    google = oauth.create_client('google')
    redirect_uri = url_for('website.authorize', _external=True)
    return google.authorize_redirect(redirect_uri)


@website.route('/authorize')
def authorize():
    google = oauth.create_client('google')
    token = google.authorize_access_token()
    resp = google.get('userinfo', token=token)
    user_info = resp.json()
    # do something with the token and profile
    session['email'] = user_info['email']
    session['first_name'] = user_info['given_name']
    return redirect('/')


@website.route('/activate', methods=['GET', 'POST'])
@auth_required
def activate():

    if database.game_status() == 1:
        return redirect(url_for('website.active'))

    if request.method == 'POST':

        form_dict = request.form.to_dict()
        form_dict['status'] = 1

        database.update(form_dict)

        return render_template('spinner.html')

    return render_template('activate.html')


@website.route('/active', methods=['GET', 'POST'])
@auth_required
def active():

    if database.game_status() == 0:
        return redirect(url_for('website.home'))

    if request.method == 'POST':

        database.update({'status': 0})

        return render_template('spinner.html')

    return render_template('active.html')


@website.route('/logout')
def logout():
    for key in list(session.keys()):
        session.pop(key)
    return redirect('/')

templates/activate.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Start a game!</title>
    <link rel="shortcut icon" type="image/png" href="static/images/icon.png">

    <!-- Import some nice fonts from Google -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&display=swap" rel="stylesheet">

    <link href="static/styles/app.css " rel="stylesheet">

    <style>
      .logo {
        width: 20%;
        padding: 40px;
        padding-left: 40%;
        padding-right: 40%;
      }
    </style>

    <script src="static/scripts/app.js"></script>

  </head>
  <body>

    <div class='topnav'>
      <img class="logo" src="static/images/logo.png">
    </div>

    <form id="form" class="center" action="{{ url_for('website.activate') }}" method="post">

      <select id="product_select" class="select_menu" name="product" required>
        <option disabled selected value> SELECT PRODUCT </option>
        <option value="donut">Donuts</option>
        <option value="muffin">Muffins</option>
        <option value="pie">Apple Pie</option>
        <option value="cookie">Cookies</option>
        <option value="fry">Large Fries</option>
        <option value="hashbrown">Hash Browns</option>
        <option value="coffee">Upsize Coffee</option>
      </select>

      <select id="duration_select" class="select_menu" name="duration" required>
        <option disabled selected value> SELECT DURATION </option>
        <option value='1'>1 hour</option>
        <option value='2'>2 hours</option>
        <option value='3'>3 hours</option>
        <option value='4'>4 hours</option>
      </select>

      <p>CREW NAMES</p>
      <input placeholder="LANE 1" maxlength="9" style="margin-bottom: 20px;" class="input" type="text" name="name1" value="">
      <input placeholder="LANE 2" maxlength="9" style="margin-bottom: 20px;" class="input" type="text" name="name2" value="">
      <input placeholder="COUNTER" maxlength="9" class="input" type="text" name="name3" value="">

      <input class="button" type="submit" value="START!">
    </form>

  </body>
</html>

templates/active.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Game in progress...</title>
    <link rel="shortcut icon" type="image/png" href="static/images/icon.png">

    <!-- Import some nice fonts from Google -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&display=swap" rel="stylesheet">

    <link href="static/styles/app.css " rel="stylesheet">

    <script src="static/scripts/app.js"></script>

  </head>
  <body>

    <div class='topnav'>
      <img class="logo" src="static/images/logo.png">
    </div>

    <form id="form" class="center" onsubmit="return confirm('Hey!\nProgress will be lost for the active game. Are you sure you want to CANCEL the active game?')" action="{{ url_for('website.active') }}" method="post">
      <p>Game in progress...</p>
      <input class="button" style="background-color: #b30000; width: 100%; margin-left: 0; height: 12vh;" type="submit" value="CANCEL">
    </form>

  </body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Home</title>
    <link rel="shortcut icon" type="image/png" href="static/images/icon.png">

    <!-- Import some nice fonts from Google -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&display=swap" rel="stylesheet">

    <link href="static/styles/app.css" rel="stylesheet">

  </head>
  <body>

    <div class='topnav'>
      <img class="logo" src="static/images/logo.png">
    </div>

    <p>Hello, {{ dict(session).get('first_name', None) }}!</p>

    <div class="center">
      <div class="button" style="width: 100%; max-height: 200px; height: 20vh; background-image: url('static/images/button_background.png'); background-size: 120%; background-position: center;" type="button" name="button" onclick="location.href = '{{ url_for('website.activate') }}';"><p>FLOOR BOARD</p></div>
      <div class="button" style="width: 100%" type="button" name="button" onclick="location.href = '{{ url_for('website.logout') }}';"><p>LOGOUT</p></div>
    </div>

  </body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <title>Login</title>
  <link rel="shortcut icon" type="image/png" href="static/images/icon.png">

  <!-- Import some nice fonts from Google -->
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">

  <link href="static/styles/app.css" rel="stylesheet">

  <style>

  .login-center {
    background: #101010;
    margin: auto;
    margin-top: 0px;
    width: 50vh;
    max-width: 80%;
    text-align: center;
  }

  .login-logo {
    width: 80%;
    margin-bottom: 30px;
    margin-right: 10%;
    margin-left: 10%;
  }

  </style>

</head>
<body>

  <div class='topnav'>
    <img class="logo" src="static/images/logo.png">
  </div>

  <div class="login-center">

    <div class="button" style="width: 100%; height: 11vh;" onclick="location.href = '{{ url_for('website.info') }}';"><p>LEARN MORE</p></div>

    <div class="google_button" onclick="location.href = '{{ url_for('website.login') }}';"></div>


  </div>

</body>
</html>